apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: "reliability-api"
        metrics_path: /metrics # ✅ required to scrape correct endpoint
        static_configs:
          - targets: ["reliability-api-service:8001"]
