apiVersion: v1
kind: Service
metadata:
  name: kubestress-service
spec:
  type: NodePort
  selector:
    app: kubestress-dashboard
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30501 # Optional static port
