global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "reliability-api"
    metrics_path: /metrics # ✅ Correct metrics path
    static_configs:
      - targets: ["reliability-api-service:8001"]
